#!/usr/bin/expect

set ADDRESS [lindex $argv 0]
set USERNAME [lindex $argv 1]
set PASSWORD [lindex $argv 2]
set KEY_NAME [lindex $argv 3]
set TIMEOUT 15

set timeout -1

spawn ssh-copy-id -o ConnectTimeout=${TIMEOUT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${KEY_NAME} ${USERNAME}@${ADDRESS}
expect {
	-glob "assword:" {
		set timeout ${TIMEOUT}
		send -- "${PASSWORD}\n"
		exp_continue
	}
	expect eof
}
