#!/usr/bin/expect

set ADDRESS [lindex $argv 0]
set USERNAME [lindex $argv 1]
set ROOTPASS [lindex $argv 2]
set TIMEOUT 15

set timeout -1

spawn env LANG=C ssh -o ConnectTimeout=${TIMEOUT} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${ADDRESS} "gpasswd -a ${USERNAME} sudo"
expect {
	-glob "assword:" {
		set timeout ${TIMEOUT}
		send -- "${ROOTPASS}\n"
		exp_continue
	}
	expect eof
}
